### ISSUE TITLE
Pull historical data for 6pm-6pm

### ISSUE THREAD

**Issue by beamalsky** [istheweatherweird/itww_bot#11]
Proposal: 

- The bot tweets once each day at 6pm, and covers the last 24 hours in both NWS observations and historical temperatures. This will involve pulling in multiple sheets from `istheweatherweird-data-hourly`, which is a little more complicated but not a problem. This sort of lines up with NWS's [definition of a day](https://www.weather.gov/bgm/forecast_terms), which is 6am-6pm, but ensures that the bot is looking at all time that passes. It also tweets at 6pm, not midnight, which is a nicer time to tweet.
- I think it would be cool if the bot tweeted weekly recaps on Sunday at 6pm, monthly recaps on the last day of the month at 6pm, and yearly recaps (?) at 6pm on the last day of the year

@potash and @jsbj, I'm also happy to defer to your sense of these things. What do you think? We should decide this before I go much further on the bot.

**Comment by potash** [comment]
Sounds good to me! For the 24 hour averages you'll never need to pull more than 2 CSVs (you might actually only pull since they are organized by UTC date and Chicago is UTC-6 though I might be off by a fencepost) so I don't think its an issue.

By the way for the 24 hour comparisons you could even use the observations API for the historical average as well but I don't think there is any benefit. For weekly averages you can just pull ~7 CSVs. For monthly and especially yearly averages that's a lot of CSVs so better to pre-aggregate in istheweatherweird-data-hourly. When you get there let me know and I can do it.

 ---- On Thu, 20 Feb 2020 16:10:54 -0600 Bea Malsky <notifications@github.com> wrote ----

**Comment by beamalsky** [comment]
Perfect! I'm putting this down for today but I'll follow this next time I pick it up.

**Comment by beamalsky** [comment]
Oh true I think you're right, I only need to pull one! That works out nicely. It'd be great to pre-aggregate monthly and yearly averages for #6 and #7. I'm just about ready for that when you're able.
