### ISSUE TITLE
test historical temp code

### ISSUE THREAD

**Issue by potash** [istheweatherweird/itww_bot#21]
@beamalsky is there a preferred place to put tests in this repo? also should we setup travis or something to run them for PRs? I don't have much experience with that so if its easy for you to do that would be great

**Comment by beamalsky** [comment]
I usually use Travis and we can definitely set that up with pytest to run on each commit, but they've had more downtime since Microsoft bought them (lol) so I've been transitioning to Github Actions. In any case how about I set up some test infrastructure and then you can write the actual tests? Is there something you use other than pytest?

**Comment by potash** [comment]
Sounds good and yeah pytest works




---- On Tue, 03 Mar 2020 10:58:43 -0600 notifications@github.com wrote ----



I usually use Travis and we can definitely set that up with pytest to run on each commit, but they've had more downtime since Microsoft bought them (lol) so I've been transitioning to Github Actions. In any case how about I set up some test infrastructure and then you can write the actual tests? Is there something you use other than pytest?
